### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Rajkumarrmani**
Initial commit

### CODE REVIEW

**Review by anandwana001 — COMMENTED** [review]
looks like you had pushed all the code files,
please don't push build files and other unnecessary files.

**Comment by Rajkumarrmani** [comment]
> looks like you had pushed all the code files, please don't push build files and other unnecessary files.

Okay. Sure

**Comment by Rajkumarrmani** [comment]
> looks like you had pushed all the code files, please don't push build files and other unnecessary files.

Now I added .gitignore files. Can you please review it now.

**Comment by anandwana001** [comment]
> > looks like you had pushed all the code files, please don't push build files and other unnecessary files.
> 
> Now I added .gitignore files. Can you please review it now.


Still the files are here, can you clean the PR?

**Pull request closed without merging**
