### PR TITLE
Project Init

### PR DESCRIPTION
**Pull request by AmartyaSingh97**

### CODE REVIEW

**Comment by anandwana001** [comment]
@AmartyaSingh97 can we complete Day 1 task in this PR?

**Comment by AmartyaSingh97** [comment]
Yes will be done.

**Comment by anandwana001** [comment]
@AmartyaSingh97 Day 1 Task Pending

**Comment by AmartyaSingh97** [comment]
Yeah akshay i am stuck into few personal issues for two days, i will try to cover later.

**Pull request closed without merging**
